### ISSUE TITLE
Unwanted "linear_angular_cmd" output override

### ISSUE THREAD

**Issue by gabrielfpacheco** [rock-control/control-orogen-auv_raw_command_converter#4]
Hello, 

I noticed that the `linear_angular_cmd`, which should be output when `control_mode = ControlChain`, is being overridden at every iteration by the AutonomousMode, which IMHO should only output `NaN`s to the ` acc_override_command` port. 

```cpp
        case auv_raw_command_converter::ControlChain:
            if(cmd_out.allFinite())
            {
                linear_angular_cmd.linear = cmd_out.block(0,0,3,1);
                linear_angular_cmd.angular = cmd_out.block(3,0,3,1);
            }
            _linear_angular_command.write(linear_angular_cmd);
        case auv_raw_command_converter::KeepAlive:
        case auv_raw_command_converter::Autonomous:
            linear_angular_cmd.linear = base::Vector3d::Ones() * base::NaN<double>();
            linear_angular_cmd.angular = base::Vector3d::Ones() * base::NaN<double>();
            _acc_override_command.write(linear_angular_cmd);
            break;
```
https://github.com/rock-control/control-orogen-auv_raw_command_converter/blob/c41be175b1b10589be8c2ba49f5532242c4c70d4/tasks/DeviceMapper.cpp#L203

This implies in an output port which is always switching from `NaN`  to the desired value given by the device mapped. As another bad consequence, when cascading other `auv_control` tasks, they keep switching states (`RUNNING` to `INPUT_MISSING`) when the tasks cmds are coming either from a `DeviceMapper`  task directly or from a `CommandDispatcher` (which, in turn, has the `DeviceMapper`  as an input).

Is this, somehow, an expected behavior?

**Comment by saarnold** [comment]
Hello Gabriel,
thanks for reporting this issue. My guess would be that this was covered up as soon as the input device was providing samples with a high enough frequency.

**Comment by gabrielfpacheco** [comment]
I guess that could happen too. But the device would need an update frequency higher than `100 Hz` since the task is periodic with a `10 ms` period. Which is very likely not the case for my Xbox One joystick :sweat_smile:

**Comment by saarnold** [comment]
This issue was fixed with rock-control/control-orogen-auv_raw_command_converter#5
